language: nix
nix: 2.2.2

jobs:
  include:
    - stage: Build
      env: OS=linux
    - env: OS=macos
      os: osx
      # Fix OSX, see https://travis-ci.community/t/cannot-use-nix-support-on-osx/2927
      language: generic
      before_install:
      - curl https://nixos.org/nix/install | sh
      - source /Users/travis/.nix-profile/etc/profile.d/nix.sh

install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org https://hydra.iohk.io" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=" | sudo tee -a /etc/nix/nix.conf > /dev/null

script:
 - timeout 40m nix-build

notifications:
  irc:
    channels: "irc.freenode.net#leksah"
  email: true
